/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.components.iValue.impl;

import javax.swing.JButton;
import javax.swing.border.TitledBorder;
import model.Bend;
import ui.components.iValue.IValue;
import ui.components.iValue.product.BendNoviPanel;
import vrednosniValidator.VrednosniValidator;
import vrednosniValidator.impl.VrednosniValidatorDefault;

/**
 *
 * @author Aleksa
 */
public class BendUpdateDecoratorPanel extends javax.swing.JPanel  implements IValue{

    vrednosniValidator.VrednosniValidator validator;
    
    /**
     * Creates new form BendUpdateDecoratorPanel
     */
    public BendUpdateDecoratorPanel() {
        initComponents();
        preparePanel();
        validator = new VrednosniValidatorDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bendNoviPanel1 = new ui.components.iValue.product.BendNoviPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bendNoviPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bendNoviPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.components.iValue.product.BendNoviPanel bendNoviPanel1;
    // End of variables declaration//GEN-END:variables

    public BendNoviPanel getProduct(){
        return bendNoviPanel1;
    }
    public JButton getBtnUpdate(){
        return bendNoviPanel1.getBtnSacuvajBend();
    }
    
    private void preparePanel() {
        TitledBorder border = (TitledBorder) bendNoviPanel1.getBorder();
        border.setTitle("Update bend");
        bendNoviPanel1.getBtnSacuvajBend().setText("Update");
    }

    @Override
    public Object getValue() throws Exception {
        //dodaje id da bi mogao da preko njega da radi update
        return ((Bend)bendNoviPanel1.getValue())
                .appendIdIzvodjaca(bendNoviPanel1.getIdIzvodjaca());
    }

    @Override
    public void setValue(Object value) {
        bendNoviPanel1.setValue(value);
    }

    /**
     * popunjava combo box
     * @param initValue 
     */
    @Override
    public void inicialize(Object initValue) {
        this.bendNoviPanel1.inicialize(initValue);
    }

    @Override
    public void setValidator(VrednosniValidator validator) {
        bendNoviPanel1.setValidator(validator);
    }
}
