/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.components.iValue.impl;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
import model.DomainObject;
import model.StavkaNastupa;
import ui.components.tableModel.StavkaNastupaTableModel;
import vrednosniValidator.VrednosniValidator;
import vrednosniValidator.impl.VrednosniValidatorDate;
import vrednosniValidator.impl.VrednosniValidatorDefault;
import vrednosniValidator.impl.VrednosniValidatorPozitivanBroj;

/**
 *
 * @author Aleksa
 */
public class StavkaNastupaPanel extends javax.swing.JPanel implements ui.components.iValue.IValue {
    
    VrednosniValidator validator;

    /**
     * Creates new form StavkaNastupaPanel
     */
    public StavkaNastupaPanel() {
        initComponents();
        preparePanel();
        validator = new VrednosniValidatorDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaStavki = new javax.swing.JTable();
        izvodjacPanel = new ui.components.iValue.impl.AddFromComboBoxPanel();
        trajanjePanel = new ui.components.iValue.impl.InputPanelTextField();
        btnUbaciStavku = new javax.swing.JButton();
        btnIzbaciStavku = new javax.swing.JButton();
        vremePanel = new ui.components.iValue.impl.InputPanelDate();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke nastupa"));

        tabelaStavki.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Stavke", "Vreme", "Trajanje", "Izvodjac"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaStavki);

        btnUbaciStavku.setText("Ubaci");
        btnUbaciStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbaciStavkuActionPerformed(evt);
            }
        });

        btnIzbaciStavku.setText("Izbaci");
        btnIzbaciStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(trajanjePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUbaciStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIzbaciStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(vremePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(izvodjacPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(izvodjacPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vremePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trajanjePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUbaciStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIzbaciStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbaciStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbaciStavkuActionPerformed
        try {
            //treba da uzme vrednosti iz polja, da napravi stavku i da je ubaci u tabelu
            ((StavkaNastupaTableModel) tabelaStavki.getModel())
                    .ubaciStavku(new StavkaNastupa()
                            .appendVreme((Date) this.vremePanel.getValue())
                            .appendTrajanje(Long.valueOf((String) this.trajanjePanel.getValue()))
                            .appendIzvodjac((DomainObject) this.izvodjacPanel.getValue()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnUbaciStavkuActionPerformed

    private void btnIzbaciStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciStavkuActionPerformed
        //uzima iz tabele selektovanu stavku i izbacuje je iz modela
        int selectedRow = tabelaStavki.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }
        StavkaNastupa s = ((StavkaNastupaTableModel) tabelaStavki.getModel())
                .getStavkaNastupa(selectedRow);
        ((StavkaNastupaTableModel) tabelaStavki.getModel())
                .izbaciStavku(s);
        
    }//GEN-LAST:event_btnIzbaciStavkuActionPerformed

    /**
     * uzima listuStavki iz tabele
     *
     * @return
     * @throws Exception
     */
    @Override
    public Object getValue() throws Exception {
        validator.validate();
        return ((StavkaNastupaTableModel) tabelaStavki.getModel()).getListaStavki();
    }

    /**
     * ubacuje u tabelu listu stavki
     *
     * @param value
     */
    @Override
    public void setValue(Object value) {
        this.tabelaStavki.setModel(new StavkaNastupaTableModel((List<StavkaNastupa>) value));
    }

    /**
     * ubacuje u combo listu izvodjaca
     *
     * @param initValue
     */
    @Override
    public void inicialize(Object initValue) {
        this.izvodjacPanel.inicialize(initValue);
    }
    
    @Override
    public void setValidator(VrednosniValidator validator) {
        this.validator = validator;
    }

    //izvodjacPanel tabelaStavki trajanjePanel vremePanel
    private void preparePanel() {
        this.vremePanel.getJlabText().setText("Vreme:");
        this.vremePanel.getJlabError().setText("");
        this.vremePanel.inicialize(1996);
        
        
        this.trajanjePanel.getJlabText().setText("Trajanje:");
        this.trajanjePanel.getJlabError().setText("");
        this.trajanjePanel.getJtxtInput().setText("");
        this.trajanjePanel.setValidator(new VrednosniValidatorPozitivanBroj(trajanjePanel));
        
        this.izvodjacPanel.getJlabText().setText("Izvodjaci/Bendovi:");
        this.izvodjacPanel.setState("singleTake");
        
        popuniTabelu(new ArrayList<StavkaNastupa>());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzbaciStavku;
    private javax.swing.JButton btnUbaciStavku;
    private ui.components.iValue.impl.AddFromComboBoxPanel izvodjacPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaStavki;
    private ui.components.iValue.impl.InputPanelTextField trajanjePanel;
    private ui.components.iValue.impl.InputPanelDate vremePanel;
    // End of variables declaration//GEN-END:variables

    public void popuniTabelu(List<StavkaNastupa> listaStavkiNastupa) {
        tabelaStavki.setModel(new StavkaNastupaTableModel(listaStavkiNastupa));
        tabelaStavki.getColumnModel().getColumn(0).setPreferredWidth(25);
        tabelaStavki.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelaStavki.getColumnModel().getColumn(2).setPreferredWidth(50);
        tabelaStavki.getColumnModel().getColumn(3).setPreferredWidth(150);
    }
}
