/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.components.iValue.product;

import java.util.List;
import javax.swing.JButton;
import model.Bend;
import model.Izvodjac;
import ui.components.iValue.IValue;
import vrednosniValidator.VrednosniValidator;
import vrednosniValidator.impl.VrednosniValidatorDefault;
import vrednosniValidator.impl.VrednosniValidatorEmail;
import vrednosniValidator.impl.VrednosniValidatorTelefon;

/**
 *
 * @author Aleksa
 */
public class BendNoviPanel extends javax.swing.JPanel implements IValue {

    private VrednosniValidator validator;

    /**
     * Creates new form BendNoviPanel
     */
    public BendNoviPanel() {
        initComponents();
        preparePanel();
        validator = new VrednosniValidatorDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idPanel = new ui.components.iValue.impl.InputPanelTextField();
        nazivBendaPanel = new ui.components.iValue.impl.InputPanelTextField();
        emailPanel = new ui.components.iValue.impl.InputPanelTextField();
        telefonPanel = new ui.components.iValue.impl.InputPanelTextField();
        clanoviBendaPanel = new ui.components.iValue.impl.AddFromComboBoxPanel();
        btnSacuvajBend = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Bend Novi"));

        btnSacuvajBend.setText("Sacuvaj Bend");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nazivBendaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clanoviBendaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnSacuvajBend, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazivBendaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clanoviBendaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnSacuvajBend)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Object getValue() throws Exception {
        validator.validate();
        Bend bend = Bend
                .bendNoviFactory((String) nazivBendaPanel.getValue(),
                        (String) emailPanel.getValue(),
                        (String) telefonPanel.getValue());
        bend.setClanoviBenda((List<Izvodjac>) clanoviBendaPanel.getValue());
        System.out.println("lista izvodjaca koja je ubacena u bend za slanje:\n" + bend.getClanoviBenda());
        return bend;
    }

    /**
     * postavlja Bend na panel
     *
     * @param value
     */
    @Override
    public void setValue(Object value) {
        if (value instanceof Bend) {
            Bend bend = (Bend) value;
            idPanel.setValue(bend.getIdIzvodjaca());
            nazivBendaPanel.setValue(bend.getNazivBenda());
            emailPanel.setValue(bend.getEmail());
            telefonPanel.setValue(bend.getTelefon());
            clanoviBendaPanel.setValue(bend.getClanoviBenda());
        }
    }

    /**
     * popunjava combo box
     *
     * @param initValue List<Izvodjac>
     */
    @Override
    public void inicialize(Object initValue) {
        if (initValue == null) {
            return;
        }
        List<Izvodjac> listaIzvodjaca = (List<Izvodjac>) initValue;
        if (listaIzvodjaca.size() == 0) {
            return;
        }
        System.out.println("lista izvodjaca primljena u inicialize kod BendNoviPanel:");
        System.out.println(listaIzvodjaca);
        this.clanoviBendaPanel.inicialize(listaIzvodjaca);
    }

    @Override
    public void setValidator(VrednosniValidator validator) {
        this.validator = validator;
    }

    private void preparePanel() {
        this.idPanel.getJlabText().setText("ID Benda:");
        this.idPanel.getJlabError().setText("");
        this.idPanel.getJtxtInput().setText("");
        this.idPanel.getJtxtInput().setEnabled(false);

        this.nazivBendaPanel.getJlabText().setText("Naziv benda:");
        this.nazivBendaPanel.getJlabError().setText("");
        this.nazivBendaPanel.getJtxtInput().setText("");

        this.emailPanel.getJlabText().setText("Email:");
        this.emailPanel.getJlabError().setText("");
        this.emailPanel.getJtxtInput().setText("");
        this.emailPanel.setValidator(new VrednosniValidatorEmail(emailPanel));

        this.telefonPanel.getJlabText().setText("Telefon:");
        this.telefonPanel.getJlabError().setText("");
        this.telefonPanel.getJtxtInput().setText("");
        this.telefonPanel.setValidator(new VrednosniValidatorTelefon(telefonPanel));

        this.clanoviBendaPanel.getJlabText().setText("Izaberite clanove:");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvajBend;
    private ui.components.iValue.impl.AddFromComboBoxPanel clanoviBendaPanel;
    private ui.components.iValue.impl.InputPanelTextField emailPanel;
    private ui.components.iValue.impl.InputPanelTextField idPanel;
    private ui.components.iValue.impl.InputPanelTextField nazivBendaPanel;
    private ui.components.iValue.impl.InputPanelTextField telefonPanel;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnSacuvajBend() {
        return btnSacuvajBend;
    }

    public Long getIdIzvodjaca() throws Exception {
        return Long.valueOf((String)idPanel.getValue());
    }

}
