/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.components.iValue.product;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Bend;
import ui.components.iValue.IValue;
import ui.components.iValue.impl.BendUpdateDecoratorPanel;
import ui.components.tableModel.BendTableModel;
import vrednosniValidator.VrednosniValidator;
import vrednosniValidator.impl.VrednosniValidatorDefault;

/**
 *
 * @author Aleksa
 */
public class BendIzmeniPanel extends javax.swing.JPanel implements IValue {

    VrednosniValidator validator;

    /**
     * Creates new form BendIzmeniPanel
     */
    public BendIzmeniPanel() {
        initComponents();
        preparePanel();
        validator = new VrednosniValidatorDefault();
        txtKriterijum.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaBendova = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comboKriterijum = new javax.swing.JComboBox<>();
        txtKriterijum = new javax.swing.JTextField();
        btnPretraziPoKriterijumu = new javax.swing.JButton();
        btnUcitaj = new javax.swing.JButton();
        bendUpdateDecoratorPanel1 = new ui.components.iValue.impl.BendUpdateDecoratorPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Izmena Bend"));

        tabelaBendova.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Naziv benda", "Email", "Telefon", "Tip"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaBendova);

        jLabel1.setText("Kriterijum:");

        comboKriterijum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "naziv benda", "email", "telefon" }));

        txtKriterijum.setText("unesite kriterijum");

        btnPretraziPoKriterijumu.setText("Pretrazi po kriterijumu");

        btnUcitaj.setText("Ucitaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboKriterijum, 0, 101, Short.MAX_VALUE))
                            .addComponent(txtKriterijum)
                            .addComponent(btnPretraziPoKriterijumu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUcitaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(bendUpdateDecoratorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraziPoKriterijumu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUcitaj, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bendUpdateDecoratorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ucima vrednost iz update panela i vraca bendZaUpdate
     * @return
     * @throws Exception 
     */
    @Override
    public Object getValue() throws Exception {
        validator.validate();
        return this.bendUpdateDecoratorPanel1.getValue();
    }

    /**
     * postavlja bend u update panel
     * @param value 
     */
    @Override
    public void setValue(Object value) {
        this.bendUpdateDecoratorPanel1.setValue(value);
    }

    /**
     * popunjava combo box
     *
     * @param initValue List<Izvodjac>
     */
    @Override
    public void inicialize(Object initValue) {
        bendUpdateDecoratorPanel1.inicialize(initValue);
    }

    @Override
    public void setValidator(VrednosniValidator validator) {
        this.validator = validator;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.components.iValue.impl.BendUpdateDecoratorPanel bendUpdateDecoratorPanel1;
    private javax.swing.JButton btnPretraziPoKriterijumu;
    private javax.swing.JButton btnUcitaj;
    private javax.swing.JComboBox<String> comboKriterijum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaBendova;
    private javax.swing.JTextField txtKriterijum;
    // End of variables declaration//GEN-END:variables

    private void preparePanel() {
        popuniTabelu(new ArrayList<Bend>());
    }

    public JButton getBtnPretraziPoKriterijumu() {
        return btnPretraziPoKriterijumu;
    }

    public JButton getBtnUpdate() {
        return bendUpdateDecoratorPanel1.getBtnUpdate();
    }

    public JButton getBtnUcitaj() {
        return btnUcitaj;
    }
    public BendUpdateDecoratorPanel getIzvodjacUpdateDecoratorPanel1() {
        return bendUpdateDecoratorPanel1;
    }

    public JTable getTabelaBendova() {
        return tabelaBendova;
    }

    public String getSelektovanKriterijum() {
        return (String) this.comboKriterijum.getSelectedItem();
    }

    public JTextField getTxtKriterijum() {
        return txtKriterijum;
    }

    /**
     * popunjava tabelu sa listom
     *
     * @param listaIzvodjacaSaKriterijumom
     */
    public void popuniTabelu(List<Bend> listaBendova) {
        tabelaBendova.setModel(new BendTableModel(listaBendova));
        tabelaBendova.getColumnModel().getColumn(0).setPreferredWidth(25);
        tabelaBendova.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelaBendova.getColumnModel().getColumn(2).setPreferredWidth(130);
        tabelaBendova.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabelaBendova.getColumnModel().getColumn(4).setPreferredWidth(50);
    }
}
