/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.components.iValue.product;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Izvodjac;
import model.VrstaIzvodjaca;
import ui.components.iValue.IValue;
import ui.components.iValue.impl.IzvodjacUpdateDecoratorPanel;
import ui.components.tableModel.IzvodjaciTableModel;
import vrednosniValidator.VrednosniValidator;
import vrednosniValidator.impl.VrednosniValidatorDefault;

/**
 *
 * @author Aleksa
 */
public class IzvodjacIzmeniPanel extends javax.swing.JPanel implements IValue {

    VrednosniValidator validator;

    /**
     * Creates new form IzvodjacIzmeniPanel
     */
    public IzvodjacIzmeniPanel() {
        initComponents();
        preparePanel();
        validator = new VrednosniValidatorDefault();
        txtKriterijum.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaIzvodjaca = new javax.swing.JTable();
        btnPretraziPoKriterijumu = new javax.swing.JButton();
        btnUcitaj = new javax.swing.JButton();
        izvodjacUpdateDecoratorPanel1 = new ui.components.iValue.impl.IzvodjacUpdateDecoratorPanel();
        jLabel1 = new javax.swing.JLabel();
        txtKriterijum = new javax.swing.JTextField();
        comboKriterijum = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Izmena Izvodjaca"));

        tabelaIzvodjaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Izvodjaca", "Ime", "Prezime", "Pol", "Email", "Telefon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaIzvodjaca);

        btnPretraziPoKriterijumu.setText("Pretrazi po kriterijumu");

        btnUcitaj.setText("Ucitaj");

        jLabel1.setText("Kriterijum:");

        txtKriterijum.setText("unesite kriterijum");
        txtKriterijum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKriterijumActionPerformed(evt);
            }
        });

        comboKriterijum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "idIzvodjac", "ime", "prezime", "email", "telefon", "pol" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPretraziPoKriterijumu, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(btnUcitaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboKriterijum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtKriterijum)))
                    .addComponent(izvodjacUpdateDecoratorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretraziPoKriterijumu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnUcitaj, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(izvodjacUpdateDecoratorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtKriterijumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKriterijumActionPerformed
        txtKriterijum.requestFocus();
        txtKriterijum.selectAll();
    }//GEN-LAST:event_txtKriterijumActionPerformed

    /**
     * ucima vrednost iz updatePanela
     * @return Izvodjac - izvodjacZaUpdate
     * @throws Exception 
     */
    @Override
    public Object getValue() throws Exception {
        validator.validate();
        return this.izvodjacUpdateDecoratorPanel1.getValue();
    }

    /**
     * postavlja Izvojdaca u updatePanel
     * @param value 
     */
    @Override
    public void setValue(Object value) {
        izvodjacUpdateDecoratorPanel1.setValue(value);
    }

    /**
     * za sada ne radi nista
     * @param initValue 
     */
    @Override
    public void inicialize(Object initValue) {
        
    }

    @Override
    public void setValidator(VrednosniValidator validator) {
        this.validator = validator;
    }

    private void preparePanel() {
        
        popuniTabelu(new ArrayList<Izvodjac>());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretraziPoKriterijumu;
    private javax.swing.JButton btnUcitaj;
    private javax.swing.JComboBox<String> comboKriterijum;
    private ui.components.iValue.impl.IzvodjacUpdateDecoratorPanel izvodjacUpdateDecoratorPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaIzvodjaca;
    private javax.swing.JTextField txtKriterijum;
    // End of variables declaration//GEN-END:variables

    public void popuniComboBox(List<VrstaIzvodjaca> listVrstaIzvodjaca) {
        this.izvodjacUpdateDecoratorPanel1.inicialize(listVrstaIzvodjaca);
    }

    public JButton getBtnPretraziPoKriterijumu() {
        return btnPretraziPoKriterijumu;
    }

    public JButton getBtnUpdate() {
        return izvodjacUpdateDecoratorPanel1.getBtnUpdate();
    }

    public JButton getBtnUcitaj() {
        return btnUcitaj;
    }

    public IzvodjacUpdateDecoratorPanel getIzvodjacUpdateDecoratorPanel1() {
        return izvodjacUpdateDecoratorPanel1;
    }

    public JTable getTabelaIzvodjaca() {
        return tabelaIzvodjaca;
    }

    public String getSelektovanKriterijum() {
        return (String) this.comboKriterijum.getSelectedItem();
    }

    public JTextField getTxtKriterijum() {
        return txtKriterijum;
    }

    /**
     * popunjava tabelu sa listom
     *
     * @param listaIzvodjacaSaKriterijumom
     */
    public void popuniTabelu(List<Izvodjac> listaIzvodjacaSaKriterijumom) {
        tabelaIzvodjaca.setModel(new IzvodjaciTableModel(listaIzvodjacaSaKriterijumom));
        tabelaIzvodjaca.getColumnModel().getColumn(0).setPreferredWidth(25);
        tabelaIzvodjaca.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelaIzvodjaca.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabelaIzvodjaca.getColumnModel().getColumn(3).setPreferredWidth(130);
        tabelaIzvodjaca.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabelaIzvodjaca.getColumnModel().getColumn(5).setPreferredWidth(50);
    }


}
