/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.components.iValue.product;

import java.util.Arrays;
import java.util.List;
import javax.swing.JButton;
import model.Izvodjac;
import model.Menadzer;
import model.Pol;
import model.VrstaIzvodjaca;
import ui.components.iValue.IValue;
import ui.components.iValue.impl.AddFromComboBoxPanel;
import vrednosniValidator.VrednosniValidator;
import vrednosniValidator.impl.VrednosniValidatorDefault;
import vrednosniValidator.impl.VrednosniValidatorEmail;
import vrednosniValidator.impl.VrednosniValidatorTelefon;

/**
 *
 * @author Aleksa
 */
public class IzvodjacNoviPanel extends javax.swing.JPanel implements IValue{

    VrednosniValidator validator;
    /**
     * Creates new form MenadzerNoviPanel
     */
    public IzvodjacNoviPanel() {
        initComponents();
        validator = new VrednosniValidatorDefault();
        preparePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idIzvodjacPanel = new ui.components.iValue.impl.InputPanelTextField();
        imePanel = new ui.components.iValue.impl.InputPanelTextField();
        prezimePanel = new ui.components.iValue.impl.InputPanelTextField();
        emailPanel = new ui.components.iValue.impl.InputPanelTextField();
        telefonPanel = new ui.components.iValue.impl.InputPanelTextField();
        polPanel = new ui.components.iValue.impl.InputPanelComboBox();
        vrstaIzvodjacaPanel = new ui.components.iValue.impl.AddFromComboBoxPanel();
        btnSacuvajIzvodjaca = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Novi Izvojdac"));

        btnSacuvajIzvodjaca.setText("Sacuvaj Izvodjaca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idIzvodjacPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prezimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(vrstaIzvodjacaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(polPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSacuvajIzvodjaca, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telefonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idIzvodjacPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prezimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(polPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnSacuvajIzvodjaca))
                    .addComponent(vrstaIzvodjacaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Object getValue() throws Exception {
        validator.validate();
        Izvodjac izvodjac = Izvodjac
                .izvodjacNoviFactory((String) imePanel.getValue(),
                        (String) prezimePanel.getValue(),
                        (String) emailPanel.getValue(),
                        (String) telefonPanel.getValue(),
                        (Pol) polPanel.getValue());
        izvodjac.setListaVrsta((List<VrstaIzvodjaca>) vrstaIzvodjacaPanel.getValue());
        System.out.println("lista vrsta izvodjaca koja je ubacena u izvodjaca za slanje:\n"+izvodjac.getListaVrsta());
        return izvodjac;
    }

    @Override
    public void setValue(Object value) {
        if (value instanceof Izvodjac) {
            Izvodjac izvodjac = (Izvodjac) value;
            idIzvodjacPanel.setValue(izvodjac.getIdIzvodjac());
            imePanel.setValue(izvodjac.getIme());
            prezimePanel.setValue(izvodjac.getPrezime());
            emailPanel.setValue(izvodjac.getEmail());
            telefonPanel.setValue(izvodjac.getTelefon());
            polPanel.setValue(izvodjac.getPol());
            vrstaIzvodjacaPanel.setValue(izvodjac.getListaVrsta());
        }else return;
    }

    @Override
    public void inicialize(Object initValue) {
        this.idIzvodjacPanel.setValue("0");
    }

    @Override
    public void setValidator(VrednosniValidator validator) {
        this.validator = validator;
    }

    private void preparePanel() {
        this.idIzvodjacPanel.getJlabText().setText("ID Izvodjaca:");
        this.idIzvodjacPanel.getJlabError().setText("");
        this.idIzvodjacPanel.getJtxtInput().setText("");
        this.idIzvodjacPanel.getJtxtInput().setEnabled(false);

        this.imePanel.getJlabText().setText("Ime Izvodjaca:");
        this.imePanel.getJlabError().setText("");
        this.imePanel.getJtxtInput().setText("");

        this.prezimePanel.getJlabText().setText("Prezime Izvodjaca:");
        this.prezimePanel.getJlabError().setText("");
        this.prezimePanel.getJtxtInput().setText("");

        this.emailPanel.getJlabText().setText("Email:");
        this.emailPanel.getJlabError().setText("");
        this.emailPanel.getJtxtInput().setText("");
        this.emailPanel.setValidator(new VrednosniValidatorEmail(emailPanel));

        this.telefonPanel.getJlabText().setText("Telefon:");
        this.telefonPanel.getJlabError().setText("");
        this.telefonPanel.getJtxtInput().setText("");
        this.telefonPanel.setValidator(new VrednosniValidatorTelefon(telefonPanel));

        this.polPanel.getJlabText().setText("Pol:");
        this.polPanel.getJlabError().setText("");
        this.polPanel.inicialize(Arrays.asList(new Pol[]{Pol.MALE, Pol.FEMALE}));
        
        this.vrstaIzvodjacaPanel.getJlabText().setText("Vrste Izvodjaca:");
        //provera da li radi
        this.vrstaIzvodjacaPanel.inicialize(Arrays.asList(new Menadzer[]{Menadzer.menadzerLoginFactory("username", "password")}));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvajIzvodjaca;
    private ui.components.iValue.impl.InputPanelTextField emailPanel;
    private ui.components.iValue.impl.InputPanelTextField idIzvodjacPanel;
    private ui.components.iValue.impl.InputPanelTextField imePanel;
    private ui.components.iValue.impl.InputPanelComboBox polPanel;
    private ui.components.iValue.impl.InputPanelTextField prezimePanel;
    private ui.components.iValue.impl.InputPanelTextField telefonPanel;
    private ui.components.iValue.impl.AddFromComboBoxPanel vrstaIzvodjacaPanel;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnSacuvajIzvodjaca() {
        return btnSacuvajIzvodjaca;
    }

    public void popuniComboBox(List<VrstaIzvodjaca> listVrstaIzvodjaca) {
        this.vrstaIzvodjacaPanel.inicialize(listVrstaIzvodjaca);
    }

    public AddFromComboBoxPanel getVrstaIzvodjacaPanel() {
        return vrstaIzvodjacaPanel;
    }
    public Long getIdIzvodjaca() throws Exception{
        return Long.valueOf((String)this.idIzvodjacPanel.getValue());
    }
    
}
