/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.components.iValue.product;

import java.util.Arrays;
import model.Menadzer;
import model.Pol;
import ui.components.iValue.IValue;
import vrednosniValidator.VrednosniValidator;
import vrednosniValidator.impl.VrednosniValidatorDefault;
import vrednosniValidator.impl.VrednosniValidatorEmail;
import vrednosniValidator.impl.VrednosniValidatorTelefon;

/**
 *
 * @author Aleksa
 */
public class MenadzerNewPanel extends javax.swing.JPanel implements IValue {

    private VrednosniValidator validator;

    /**
     * Creates new form MenadzerNewPanel
     */
    public MenadzerNewPanel() {
        initComponents();
        validator = new VrednosniValidatorDefault();
        preparePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idMenadzerPanel = new ui.components.iValue.impl.InputPanelTextField();
        imeMenadzeraPanel = new ui.components.iValue.impl.InputPanelTextField();
        prezimeMenadzeraPanel = new ui.components.iValue.impl.InputPanelTextField();
        usernamePanel = new ui.components.iValue.impl.InputPanelTextField();
        passwordPanel = new ui.components.iValue.impl.InputPanelPassword();
        passwordAgainPanel = new ui.components.iValue.impl.InputPanelPassword();
        telefonPanel = new ui.components.iValue.impl.InputPanelTextField();
        emailPanel = new ui.components.iValue.impl.InputPanelTextField();
        polPanel = new ui.components.iValue.impl.InputPanelComboBox();
        btnSacuvajMenadzera = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Novi Menadzer"));

        btnSacuvajMenadzera.setText("Sacuvaj Menadzera");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idMenadzerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imeMenadzeraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prezimeMenadzeraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordAgainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telefonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 61, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(polPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(btnSacuvajMenadzera, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(idMenadzerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imeMenadzeraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prezimeMenadzeraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passwordAgainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(telefonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(polPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnSacuvajMenadzera)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Object getValue() throws Exception {
        validator.validate();
        Menadzer menadzer = Menadzer.menadzerCreateFactory(String.valueOf(usernamePanel.getValue()),
                String.valueOf(passwordPanel.getValue()),
                String.valueOf(imeMenadzeraPanel.getValue()),
                String.valueOf(prezimeMenadzeraPanel.getValue()),
                String.valueOf(telefonPanel.getValue()),
                String.valueOf(emailPanel.getValue()),
                (Pol) polPanel.getValue());
        return menadzer;
    }

    @Override
    public void setValue(Object value) {
        if (!(value instanceof Menadzer)) {
            System.out.println("GRESKA: ubaceno je nesto sto nije Menadzer u setValue()");
            return;
        }
        Menadzer menadzer = (Menadzer) value;
        idMenadzerPanel.setValue(menadzer.getIdMenadzer());
        imeMenadzeraPanel.setValue(menadzer.getImeMenadzera());
        prezimeMenadzeraPanel.setValue(menadzer.getPrezimeMenadzera());
        usernamePanel.setValue(menadzer.getUsername());
        passwordPanel.setValue(menadzer.getPassword());
        passwordAgainPanel.setValue(menadzer.getPassword());
        emailPanel.setValue(menadzer.getEmail());
        telefonPanel.setValue(menadzer.getTelefon());
        polPanel.setValue(menadzer.getPol());
    }

    @Override
    public void inicialize(Object initValue) {
        this.idMenadzerPanel.inicialize("0");
        this.imeMenadzeraPanel.inicialize("");
        this.prezimeMenadzeraPanel.inicialize("");
        this.usernamePanel.inicialize("");
        this.passwordPanel.inicialize("");
        this.passwordAgainPanel.inicialize("");
        this.emailPanel.inicialize("");
        this.telefonPanel.inicialize("");

    }

    @Override
    public void setValidator(VrednosniValidator validator) {
        this.validator = validator;
    }

    private void preparePanel() {
        this.idMenadzerPanel.getJlabText().setText("ID Menadzera:");
        this.idMenadzerPanel.getJlabError().setText("");
        this.idMenadzerPanel.getJtxtInput().setText("");
        this.idMenadzerPanel.getJtxtInput().setEnabled(false);

        this.imeMenadzeraPanel.getJlabText().setText("Ime Menadzera:");
        this.imeMenadzeraPanel.getJlabError().setText("");
        this.imeMenadzeraPanel.getJtxtInput().setText("");

        this.prezimeMenadzeraPanel.getJlabText().setText("Prezime Menadzera:");
        this.prezimeMenadzeraPanel.getJlabError().setText("");
        this.prezimeMenadzeraPanel.getJtxtInput().setText("");

        this.usernamePanel.getJlabText().setText("Username:");
        this.usernamePanel.getJlabError().setText("");
        this.usernamePanel.getJtxtInput().setText("");
        
        this.passwordPanel.getJlabText().setText("Password:");
        this.passwordPanel.getJlabError().setText("");
        this.passwordPanel.getJpassword().setText("");

        this.passwordAgainPanel.getJlabText().setText("Repeat Password:");
        this.passwordAgainPanel.getJlabError().setText("");
        this.passwordAgainPanel.getJpassword().setText("");

        this.emailPanel.getJlabText().setText("Email:");
        this.emailPanel.getJlabError().setText("");
        this.emailPanel.getJtxtInput().setText("");
        this.emailPanel.setValidator(new VrednosniValidatorEmail(emailPanel));

        this.telefonPanel.getJlabText().setText("Telefon:");
        this.telefonPanel.getJlabError().setText("");
        this.telefonPanel.getJtxtInput().setText("");
        this.telefonPanel.setValidator(new VrednosniValidatorTelefon(telefonPanel));

        this.polPanel.getJlabText().setText("Pol:");
        this.polPanel.getJlabError().setText("");
        this.polPanel.inicialize(Arrays.asList(new Pol[]{Pol.MALE, Pol.FEMALE}));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvajMenadzera;
    private ui.components.iValue.impl.InputPanelTextField emailPanel;
    private ui.components.iValue.impl.InputPanelTextField idMenadzerPanel;
    private ui.components.iValue.impl.InputPanelTextField imeMenadzeraPanel;
    private ui.components.iValue.impl.InputPanelPassword passwordAgainPanel;
    private ui.components.iValue.impl.InputPanelPassword passwordPanel;
    private ui.components.iValue.impl.InputPanelComboBox polPanel;
    private ui.components.iValue.impl.InputPanelTextField prezimeMenadzeraPanel;
    private ui.components.iValue.impl.InputPanelTextField telefonPanel;
    private ui.components.iValue.impl.InputPanelTextField usernamePanel;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnSacuvajMenadzera() {
        return btnSacuvajMenadzera;
    }

    public ui.components.iValue.impl.InputPanelPassword getPasswordAgainPanel() {
        return passwordAgainPanel;
    }

    public ui.components.iValue.impl.InputPanelPassword getPasswordPanel() {
        return passwordPanel;
    }
    
}
