/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.components.iValue.product;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Izvodjac;
import model.Nastup;
import model.VrstaIzvodjaca;
import ui.components.iValue.IValue;
import ui.components.iValue.impl.IzvodjacUpdateDecoratorPanel;
import ui.components.iValue.impl.NastupUpdateDecoratorPanel;
import ui.components.tableModel.IzvodjaciTableModel;
import ui.components.tableModel.NastupTableModel;
import vrednosniValidator.VrednosniValidator;
import vrednosniValidator.impl.VrednosniValidatorDefault;

/**
 *
 * @author Aleksa
 */
public class NastupIzmeniPanel extends javax.swing.JPanel implements IValue {

    VrednosniValidator validator;

    /**
     * Creates new form NastupIzmeniPanel
     */
    public NastupIzmeniPanel() {
        initComponents();
        preparePanel();
        validator = new VrednosniValidatorDefault();
        txtKriterijum.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaNastupa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comboKriterijum = new javax.swing.JComboBox<>();
        txtKriterijum = new javax.swing.JTextField();
        btnPretraziPoKriterijumu = new javax.swing.JButton();
        btnUcitaj = new javax.swing.JButton();
        nastupUpdateDecoratorPanel1 = new ui.components.iValue.impl.NastupUpdateDecoratorPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Nastup Izmena"));

        tabelaNastupa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Izvodjaca", "Ime", "Prezime", "Pol", "Email", "Telefon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaNastupa);

        jLabel1.setText("Kriterijum:");

        comboKriterijum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "idNastupa", "nazivNastupa", "opis", "lokacija" }));

        txtKriterijum.setText("unesite kriterijum");
        txtKriterijum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKriterijumActionPerformed(evt);
            }
        });

        btnPretraziPoKriterijumu.setText("Pretrazi po kriterijumu");

        btnUcitaj.setText("Ucitaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPretraziPoKriterijumu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUcitaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboKriterijum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nastupUpdateDecoratorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretraziPoKriterijumu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnUcitaj, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nastupUpdateDecoratorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtKriterijumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKriterijumActionPerformed
        txtKriterijum.requestFocus();
        txtKriterijum.selectAll();
    }//GEN-LAST:event_txtKriterijumActionPerformed

    /**
     * uzima vrednost iz updatePanela
     *
     * @return Nasutp - nastupZaUpdate
     * @throws Exception
     */
    @Override
    public Object getValue() throws Exception {
        validator.validate();
        return this.nastupUpdateDecoratorPanel1.getValue();
    }

    /**
     * postavlja Nastup u updatePanel
     *
     * @param value
     */
    @Override
    public void setValue(Object value) {
        nastupUpdateDecoratorPanel1.setValue(value);
    }

    /**
     * ubacuje listu Izvodjac?Bend u combo box
     *
     * @param initValue
     */
    @Override
    public void inicialize(Object initValue) {
        nastupUpdateDecoratorPanel1.inicialize(initValue);
    }

    @Override
    public void setValidator(VrednosniValidator validator) {
        this.validator = validator;
    }

    private void preparePanel() {

        popuniTabelu(new ArrayList<Nastup>());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretraziPoKriterijumu;
    private javax.swing.JButton btnUcitaj;
    private javax.swing.JComboBox<String> comboKriterijum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private ui.components.iValue.impl.NastupUpdateDecoratorPanel nastupUpdateDecoratorPanel1;
    private javax.swing.JTable tabelaNastupa;
    private javax.swing.JTextField txtKriterijum;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnPretraziPoKriterijumu() {
        return btnPretraziPoKriterijumu;
    }

    public JButton getBtnUpdate() {
        return nastupUpdateDecoratorPanel1.getBtnUpdate();
    }

    public JButton getBtnUcitaj() {
        return btnUcitaj;
    }

    public NastupUpdateDecoratorPanel getIzvodjacUpdateDecoratorPanel1() {
        return nastupUpdateDecoratorPanel1;
    }

    public JTable getTabelaNastupa() {
        return tabelaNastupa;
    }

    public String getSelektovanKriterijum() {
        return (String) this.comboKriterijum.getSelectedItem();
    }

    public JTextField getTxtKriterijum() {
        return txtKriterijum;
    }

    /**
     * popunjava tabelu sa listom
     *
     * @param listaIzvodjacaSaKriterijumom
     */
    public void popuniTabelu(List<Nastup> listanastupa) {
        tabelaNastupa.setModel(new NastupTableModel(listanastupa));
        tabelaNastupa.getColumnModel().getColumn(0).setPreferredWidth(25);
        tabelaNastupa.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelaNastupa.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabelaNastupa.getColumnModel().getColumn(3).setPreferredWidth(130);
    }
}
